#!/bin/sh
'''exec' "/Users/tomarvanshika2012gmail.com/Desktop/Child safety project fies/venv/bin/python3.10" "$0" "$@"
' '''
import sys
from av.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
